# coding=utf-8

# settings keys
# DO NOT CHANGE without updating AuthLDAPPlugin.on_settings_migrate()
AUTH_PASSWORD = "auth_password"
AUTH_USER = "auth_user"
DEFAULT_ADMIN_GROUP = "default_admin_group"
DEFAULT_USER_GROUP = "default_user_group"
OU_FILTER = "ou_filter"
OU_MEMBER_FILTER = "ou_member_filter"
OU = "ou"
LOCAL_CACHE = "local_cache",
REQUEST_TLS_CERT = "request_tls_cert"
SEARCH_BASE = "search_base"
SEARCH_FILTER = "search_filter"
SEARCH_TERM_TRANSFORM = "search_term_transform"
URI = "uri"
USERID_FIELD = "userid_field"
USERID_PATTERN = "userid_pattern"

# frequently used terms
DISTINGUISHED_NAME = "dn"

# arbitrary strings
PLUGIN_NAME = "Auth LDAP"
LDAP_PARENT_GROUP_KEY = "ldap"
LDAP_PARENT_GROUP_NAME = "LDAP-Authenticated Users"
LDAP_PARENT_GROUP_DESCRIPTION = \
    "Generated by %s plugin, with membership synced automatically based on LDAP configuration" % PLUGIN_NAME
LDAP_GROUP_KEY_PREFIX = "ldap_"
